spring.application.name=Logging_Service

# ===================================================
# SERVER CONFIGURATION
# ===================================================
server.port=8085

# ===================================================
# LOGGING CONFIGURATION
# ===================================================
logging.level.root=INFO
logging.level.com.example.Logging_Service=DEBUG
