services:

  eureka-server:
    build:
      context: ./Eureka_Server/Eureka_Server
      dockerfile: Dockerfile

    container_name: eureka-server

    ports:
      - "8761:8761"

    restart: unless-stopped

  user-mysql:
    image: mysql:8.4

    container_name: user-service-mysql

    environment:
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user_service_app
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - user-service-mysql-data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  user-service:
    build:
      context: ./User_Service
      dockerfile: Dockerfile

    container_name: user-service

    ports:
      - "8081:8081"

    environment:
      DB_URL: jdbc:mysql://user-mysql:3306/user_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: user_service_app
      DB_PASSWORD: ${USER_DB_PASSWORD}

    depends_on:
      user-mysql:
        condition: service_healthy

      eureka-server:
        condition: service_started

    restart: on-failure

  account-mysql:
    image: mysql:8.4

    container_name: account-service-mysql

    environment:
      MYSQL_DATABASE: account_service_db
      MYSQL_USER: account_service_app
      MYSQL_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3308:3306"

    volumes:
      - account-service-db:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  account-service:
    build:
      context: ./Account_Service
      dockerfile: Dockerfile

    container_name: account-service

    ports:
      - "8082:8082"

    environment:
      DB_URL: jdbc:mysql://account-mysql:3306/account_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: account_service_app
      DB_PASSWORD: ${ACCOUNT_DB_PASSWORD}

    depends_on:
      account-mysql:
        condition: service_healthy

      eureka-server:
        condition: service_started

    restart: on-failure

volumes:
  user-service-mysql-data:
  account-service-db: