# ===================================================
# APPLICATION IDENTITY
# ===================================================
spring.application.name=Transaction-Service
server.port=8083

# ===================================================
# MYSQL DATASOURCE CONFIGURATION
# ===================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================
# JPA / HIBERNATE CONFIGURATION
# ===================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# ===================================================
# LOGGING
# ===================================================
logging.level.org.hibernate.SQL=debug
logging.level.com.example.Transaction_Service=debug

# ===================================================
# ACCOUNT SERVICE
# ===================================================
account-service.url=${ACCOUNT_SERVICE_URL}

# ===================================================
# FEIGN
# ===================================================
feign.circuitbreaker.enabled=true

# ===================================================
# EUREKA
# ===================================================
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.instance.prefer-ip-address=true

interest.rate=0.05
interest.cron=0 0 0 * * *

# ==========================================
# KAFKA
# ==========================================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

transaction.kafka.topic=virtual-bank-logs