spring.application.name=User_Service

# ===================================================
# SERVER CONFIGURATION
# ===================================================
server.port=8081

# ===================================================
# MYSQL DATASOURCE CONFIGURATION
# ===================================================
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================
# JPA / HIBERNATE CONFIGURATION
# ===================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===================================================
# LOGGING CONFIGURATION
# ===================================================
logging.level.root=INFO
logging.level.com.example.User_Service=DEBUG
