services:
  mysql:
    image: mysql:8.4
    container_name: transaction-mysql

    environment:
      MYSQL_DATABASE: transaction_db
      MYSQL_USER: transaction_app
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3309:3306"

    volumes:
      - transaction-mysql-data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: transaction-service

    ports:
      - "8083:8083"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/transaction_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: transaction_app
      DB_PASSWORD: ${DB_PASSWORD}

      ACCOUNT_SERVICE_URL: http://host.docker.internal:8082

    depends_on:
      mysql:
        condition: service_healthy
      
      kafka:
        condition: service_started  

volumes:
  transaction-mysql-data: